use chrono::DateTime;
use chrono::prelude::Utc;
use token::Token;
use roll::Roll;
use parser::Program;

#[derive(Debug, Deserialize, Serialize)]
pub struct Output {
    /// The original input
    pub input: String,

    /// Errors, if any
    pub errors: Vec<String>,

    /// Timestamp
    pub executed: DateTime<Utc>,

    /// Time to execute final output
    pub execution_time: u64,

    /// Chat messages to be sent
    pub messages: Vec<String>,

    /// Program generated by the parser
    pub program: Option<Program>,

    /// Dice rolls
    pub rolls: Vec<Roll>,

    /// Tokens
    pub tokens: Vec<Token>,
 
    /// API Version
    pub version: String,
}

// #[derive(Debug, Deserialize, Serialize)]
// pub struct ErrorOutput {
    // /// Type of error
    // error: String,

    // /// Message
    // message: String
// }
